[package]
name = "licencify"
version = "0.1.0"
edition = "2024"
description = "A CLI tool to add open-source licenses to projects"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
dirs = "6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1"
toml = "0.8"
toml_edit = "0.22"
ureq = "3.0"
